AllCops:
  DisabledByDefault: true

  RubyInterpreters:
    - ruby

  Include:
    - '**/*.rb'
    - '.pryrc'

  Exclude:
    <% Dir.glob("#{__dir__}/*").grep_v(%r{#{__dir__}\/(app|lib)}).each do |dir| %>
    - <%= dir %>/**/*
    <% end %>
    - 'lib/templates/**/*'

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/BlockEndNewline:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/ElseAlignment:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: def

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around
